[package]
name = "space"
version = "0.7.2"
description = "A library for working with spatial trees and point clouds"
documentation = "https://docs.rs/space/"
repository = "https://github.com/vadixidav/space"
keywords = ["space", "pointcloud", "octree", "morton", "spatial"]
license = "MIT"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
readme = "README.md"

edition = "2018"

[dependencies]
nalgebra = { version = "0.18", default-features = false }
num-traits = { version = "0.2", default-features = false }
itertools = { version = "0.7.8", default-features = false }
either = { version = "1.5.0", default-features = false }
lru-cache = { version = "0.1.1", default-features = false }
rand = { version = "0.5.5", features = ["std"] }
smallvec = { version = "0.6.7", default-features = false }
bitintr = { version = "0.2.0", default-features = false }
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }

[dev-dependencies]
criterion = { version = "0.2", default-features = false }
glium = "0.23.0"

[profile.release]
codegen-units = 1

[[bench]]
name = "octree"
harness = false